modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="extraenchants"
version="1.0.0"
displayName="Extra Enchants (Reworked)"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Oskar W. Heineck, MCreator"

[[dependencies.extraenchants]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



[[dependencies.extraenchants]]
    modId="just_enough_items"
    mandatory=false
    ordering="NONE"
    side="BOTH"

